apiVersion: v1
kind: Service
metadata:
  name: dl-disperser-svc-0
  labels:
    app: dl-disperser
spec:
  type: NodePort
  selector:
    statefulset.kubernetes.io/pod-name: dl-disperser-0
  ports:
    - name: grpc
      port: 32000
      nodePort: 32000
      targetPort: 32000
