apiVersion: v1
kind: Service
metadata:
  name: dl-disperser-metrics-svc-0
  labels:
    app: dl-disperser
spec:
  type: ClusterIP
  selector:
    statefulset.kubernetes.io/pod-name: dl-disperser-0
  ports:
    - name: metrics
      port: 32002
      targetPort: 32002


