apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
patchesStrategicMerge:
- ./patches/node-selector.yaml
replicas:
- count: 4
  name: graph
resources:
- ../config/relay
- ../config/graph
- ../../../base/graph
images:
- name: subgraph-starter
  name: ghcr.io/layr-labs/datalayr/subgraph-starter
  newTag: v0.0.3
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
