apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../../../base/relay
- ../../../base/chain/config/prod-chain
- ../config/geth
namespace: relay
replicas:
- count: 5
  name: relay
