apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
configMapGenerator:
- files:
  - genesis.json
  name: chain-genesis
secretGenerator:
- files:
  - secret/geth-account-address
  - secret/geth-account-password
  - secret/geth-account-pk
  name: bootnode-secret
  type: Opaque
