version: '3'
services:
  grafana:
    image: grafana/grafana
    ports:
      - '3000:3000'
    volumes:
      - "./grafana/eigenda_datasource_cluster.yml:/etc/grafana/provisioning/datasources/eigenda_datasource.yml"
