apiVersion: v1
items:
- apiVersion: v1
  kind: Service
  metadata:
    annotations:
      kubectl.kubernetes.io/last-applied-configuration: |
        {"apiVersion":"v1","kind":"Service","metadata":{"annotations":{},"labels":{"app":"dl-disperser"},"name":"dl-disperser-svc-0","namespace":"default"},"spec":{"ports":[{"name":"grpc","nodePort":32000,"port":32000,"targetPort":32000}],"selector":{"statefulset.kubernetes.io/pod-name":"dl-disperser-0"},"type":"NodePort"}}
    creationTimestamp: "2022-12-10T00:43:52Z"
    labels:
      app: dl-disperser
    name: dl-disperser-svc-0
    namespace: default
    resourceVersion: "13293993"
    uid: 76307daa-1921-4dd3-a98b-90aa51ffd939
  spec:
    clusterIP: 172.20.154.224
    clusterIPs:
    - 172.20.154.224
    externalTrafficPolicy: Cluster
    internalTrafficPolicy: Cluster
    ipFamilies:
    - IPv4
    ipFamilyPolicy: SingleStack
    ports:
    - name: grpc
      nodePort: 32000
      port: 32000
      protocol: TCP
      targetPort: 32000
    selector:
      statefulset.kubernetes.io/pod-name: dl-disperser-0
    sessionAffinity: None
    type: NodePort
  status:
    loadBalancer: {}
kind: List
metadata:
  resourceVersion: ""
