apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: blockscout
spec:
  template:
    spec:
      containers:
        - name: blockscout-node
          env:
            - name: ETHEREUM_JSONRPC_HTTP_URL
              value: https://rpc.eigenda.xyz
