apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: dl-disperser
spec:
  template:
    spec:
      nodeSelector:
        app: eigenda
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: dl-retriever
spec:
  template:
    spec:
      nodeSelector:
        app: eigenda
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: dl-node
spec:
  template:
    spec:
      nodeSelector:
        app: eigenda
