apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../../../base/docs/
configMapGenerator:
- envs:
  - config/docs-oauth2.env
  name: docs-oauth2
generatorOptions:
  disableNameSuffixHash: true
