apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:
  app: dl-disperser
configMapGenerator:
- envs:
  - dl-disperser-0.env
  name: dl-disperser-0
generatorOptions:
  disableNameSuffixHash: true
