apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:
  app: graph
configMapGenerator:
- files:
  - subgraph.yaml
  name: subgraph-config
- files:
  - networks.json
  name: graph-network-config
