apiVersion: v1
kind: Service
metadata:
  name: prometheus-0
  labels:
    app: prometheus
spec:
  type: NodePort
  selector:
    app: prometheus
  ports:
    - name: http
      port: 9090 
      nodePort: 34000
      targetPort: 9090
