apiVersion: v1
items:
- apiVersion: v1
  kind: Service
  metadata:
    annotations:
      kubectl.kubernetes.io/last-applied-configuration: |
        {"apiVersion":"v1","kind":"Service","metadata":{"annotations":{},"labels":{"app":"dl-disperser"},"name":"dl-disperser-svc-0","namespace":"default"},"spec":{"ports":[{"name":"grpc","nodePort":32001,"port":32001,"targetPort":32001},{"name":"metrics","nodePort":32000,"port":32000,"targetPort":32000}],"selector":{"statefulset.kubernetes.io/pod-name":"dl-disperser-0"},"type":"NodePort"}}
    creationTimestamp: "2022-12-10T02:37:54Z"
    labels:
      app: dl-disperser
    name: dl-disperser-svc-0
    namespace: default
    resourceVersion: "13328554"
    uid: 01b6addb-9182-4c92-9e98-63869523f983
  spec:
    clusterIP: 172.20.108.227
    clusterIPs:
    - 172.20.108.227
    externalTrafficPolicy: Cluster
    internalTrafficPolicy: Cluster
    ipFamilies:
    - IPv4
    ipFamilyPolicy: SingleStack
    ports:
    - name: grpc
      nodePort: 32001
      port: 32001
      protocol: TCP
      targetPort: 32001
    - name: metrics
      nodePort: 32000
      port: 32000
      protocol: TCP
      targetPort: 32000
    selector:
      statefulset.kubernetes.io/pod-name: dl-disperser-0
    sessionAffinity: None
    type: NodePort
  status:
    loadBalancer: {}
kind: List
metadata:
  resourceVersion: ""
