apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
images:
- name: ghcr.io/layr-labs/datalayr/dl-disperser
  newTag: master
- name: ghcr.io/layr-labs/datalayr/dl-retriever
  newTag: master
- name: ghcr.io/layr-labs/datalayr/dl-node
  newTag: master
- name: ghcr.io/layr-labs/datalayr/init-container-data-loader
  newTag: point-3000
patchesStrategicMerge:
- ./patches/num-graphs.yaml
- ./patches/num-relays.yaml
resources:
- ../config/relay
- ../config/node
- ./disperser
- ./disperser/env
- ./node
- ./node/env
- ./retriever/env
- ./retriever
