apiVersion: v1
kind: Service
metadata:
  name: blobs-ingress-svc
spec:
  selector:
    app: blobs
  ports:
    - name: http
      port: 80
      targetPort: 4182
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: blobs-ingress
  annotations:
    cert-manager.io/issuer: "letsencrypt-prod"
spec:
  ingressClassName: nginx
  tls:
  - hosts:
    - blobs.eigenda.xyz
    secretName: blobs-tls
  rules:
  - host: blobs.eigenda.xyz
    http:
      paths:
      - pathType: Prefix
        path: "/"
        backend:
          service:
            name: blobs-ingress-svc
            port:
              number: 80
