apiVersion: v1
kind: Service
metadata:
  name: blocks-ingress-svc
spec:
  selector:
    app: blockscout
  ports:
    - name: http
      port: 80
      targetPort: 4180
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: blocks-ingress
  annotations:
    cert-manager.io/issuer: "letsencrypt-prod"
spec:
  ingressClassName: nginx
  tls:
  - hosts:
    - blocks.eigenda.xyz
    secretName: blockscout-tls
  rules:
  - host: blocks.eigenda.xyz
    http:
      paths:
      - pathType: Prefix
        path: "/"
        backend:
          service:
            name: blocks-ingress-svc
            port:
              number: 80
