apiVersion: v1
kind: Service
metadata:
  name: cache-ingress-svc
spec:
  selector:
    app: cache
  ports:
    - name: http
      port: 80
      targetPort: 5001
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: cache-ingress
  annotations:
    cert-manager.io/issuer: "letsencrypt-prod"
spec:
  ingressClassName: nginx
  tls:
  - hosts:
    - cache.eigenda.xyz
    secretName: cache-tls
  rules:
  - host: cache.eigenda.xyz
    http:
      paths:
      - pathType: Prefix
        path: "/"
        backend:
          service:
            name: cache-ingress-svc
            port:
              number: 80
