apiVersion: v1
kind: Service
metadata:
  name: graph-ingress-svc
spec:
  selector:
    app: graph
  ports:
    - name: http
      port: 80
      targetPort: 8000
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: graph-ingress
  annotations:
    cert-manager.io/issuer: "letsencrypt-prod"
spec:
  ingressClassName: nginx
  tls:
  - hosts:
    - graph.eigenda.xyz
    secretName: graph-tls
  rules:
  - host: graph.eigenda.xyz
    http:
      paths:
      - pathType: Prefix
        path: "/"
        backend:
          service:
            name: graph-ingress-svc
            port:
              number: 80
