apiVersion: v1
kind: Service
metadata:
  name: dl-node-0
  labels:
    app: dl-node
spec:
  type: NodePort
  externalTrafficPolicy: Local
  selector:
    statefulset.kubernetes.io/pod-name: dl-node-0
  ports:
    - name: grpc
      port: 32002
      nodePort: 32002
      targetPort: 32002
