apiVersion: v1
kind: Service
metadata:
  name: dl-node-metrics-0
  labels:
    app: dl-node
spec:
  type: ClusterIP
  selector:
    statefulset.kubernetes.io/pod-name: dl-node-0
  ports:
    - name: metrics
      port: 32002
      targetPort: 32002

