version: '3'
services:
  geth:
    image: ethereum/client-go:v1.10.17
    pull_policy: always
    container_name: geth
    restart: unless-stopped
    ports:
      - 30303:30303
      - 30303:30303/udp
      - 8545:8545
      - 8546:8546
      - 8551:8551
    volumes:
      - ${PWD}/geth-node/data:/root/.ethereum
      - ${PWD}/geth-node/secret:/secret
    stop_signal: SIGINT
    stop_grace_period: 2m
    healthcheck:
      test: [ "CMD-SHELL", "geth attach --exec eth.blockNumber" ]
      interval: 10s
      timeout: 5s
      retries: 5
    command:
      - --datadir=/root/.ethereum
      - --networkid=${GETH_CHAINID}
      - --ws
      - --ws.addr=0.0.0.0
      - --http
      - --http.addr=0.0.0.0
      - --http.vhosts=*
      - --http.api=eth,net,web3,txpool,debug
      - --nodiscover
      - --netrestrict=127.0.0.1/0
      - --unlock=${GETH_UNLOCK_ADDRESS}
      - --mine
      - --allow-insecure-unlock
      - --password=/secret/geth-account-password
      - --rpc.gascap=0
      - --miner.gasprice=1
      - --rpc.allow-unprotected-txs
      - --miner.gaslimit=2922337203600000
      - --maxpeers=200
    logging:
      driver: json-file
      options:
        max-size: 2m
        max-file: 10

  graph-node:
    image: graphprotocol/graph-node:v0.28.2
    ports:
      - '8000:8000'
      - '8001:8001'
      - '8020:8020'
      - '8030:8030'
      - '8040:8040'
    depends_on:
      - ipfs
      - postgres
    extra_hosts:
      - ${HOST_IP}:host-gateway
    environment:
      postgres_host: postgres
      postgres_user: graph-node
      postgres_pass: let-me-in
      postgres_db: graph-node
      ipfs: 'ipfs:5001'
      ethereum: 'mainnet:http://${HOST_IP}:8545'
      GRAPH_LOG: info
      BLOCK_INGESTOR: default

  ipfs:
    image: ipfs/go-ipfs:v0.10.0
    ports:
      - '5001:5001'
    volumes:
      - ./graph-node/data/ipfs:/data/ipfs

  postgres:
    image: postgres
    ports:
      - '5432:5432'
    command:
      [
        "postgres",
        "-cshared_preload_libraries=pg_stat_statements"
      ]
    environment:
      POSTGRES_USER: graph-node
      POSTGRES_PASSWORD: let-me-in
      POSTGRES_DB: graph-node
      PGDATA: "/data/postgres"
    volumes:
      - ./graph-node/data/postgres:/var/lib/postgresql/data

networks:
  default:
    name: datalayr_integration
