dataSources:
    - kind: ethereum
      mapping:
        abis:
            - file: ./abis/BLSRegistry.json
              name: BLSRegistry
        apiVersion: 0.0.7
        entities:
            - Registration
        eventHandlers:
            - event: Registration(indexed address,bytes32,(uint256,uint256),uint32,bytes32,string)
              handler: handleRegistration
            - event: SocketUpdate(address,string)
              handler: handleSocketUpdate
        blockHandlers: []
        file: ./src/bls-registry.ts
        kind: ethereum/events
        language: wasm/assemblyscript
      name: BLSRegistry
      network: mainnet
      source:
        abi: BLSRegistry
        address: 6dde959D3815D27601A92DBB11539b0c7F0e12CB
        startBlock: 12707
    - kind: ethereum
      mapping:
        abis:
            - file: ./abis/DataLayrServiceManager.json
              name: DataLayrServiceManager
        apiVersion: 0.0.7
        entities:
            - ConfirmDataStore
            - InitDataStore
            - SignatoryRecord
        eventHandlers:
            - event: InitDataStore(address,((bytes32,uint32,uint32,uint32,uint32,uint96,address,bytes32),uint8,uint256,uint32),bytes)
              handler: handleInitDataStore
            - event: SignatoryRecord(bytes32,uint32,uint256,uint256,bytes32[])
              handler: handleSignatoryRecord
        blockHandlers: []
        file: ./src/dl-service-manager.ts
        kind: ethereum/events
        language: wasm/assemblyscript
      name: DataLayrServiceManager
      network: mainnet
      source:
        abi: DataLayrServiceManager
        address: e632085AA39461805bD0dfEEB3f856D9b5379436
        startBlock: 12707
    - kind: ethereum
      mapping:
        abis:
            - file: ./abis/BLSPublicKeyCompendium.json
              name: BLSPublicKeyCompendium
        apiVersion: 0.0.7
        entities:
            - NewPubkeyRegistration
        eventHandlers:
            - event: NewPubkeyRegistration(address,(uint256,uint256),(uint256[2],uint256[2]))
              handler: handleNewPubkeyRegistration
        blockHandlers: []
        file: ./src/bls-pubkey-compendium.ts
        kind: ethereum/events
        language: wasm/assemblyscript
      name: BLSPublicKeyCompendium
      network: mainnet
      source:
        abi: BLSPublicKeyCompendium
        address: A08adCe9CD95ac7ac4Ca7b83c899FDd2717bEB77
        startBlock: 12707
schema:
    file: ./schema.graphql
specVersion: 0.0.5
