apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
configMapGenerator:
- files:
  - ./scripts/start.sh
  name: relay-start-script
resources:
- statefulset.yaml
- namespace.yaml
commonLabels:
  app: relay
namespace: relay