apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../../../base/blockscout/
configMapGenerator:
- envs:
  - config/blockscout-oauth2.env
  name: blockscout-oauth2
generatorOptions:
  disableNameSuffixHash: true
patches:
- path: patches/rpc.yaml
