apiVersion: v1
kind: Service
metadata:
  name: dl-retriever-svc-0
  labels:
    app: dl-retriever
spec:
  type: NodePort
  selector:
    statefulset.kubernetes.io/pod-name: dl-retriever-0
  ports:
    - name: grpc
      port: 32001
      nodePort: 32001
      targetPort: 32001
