name: unit-tests
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  unit-tests:
    name: Unit Tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-go@v3
        with:
          go-version: '1.18' # The Go version to download (if necessary) and use.
      - run: go version

      - name: Checkout DataLayr
        uses: actions/checkout@v3

      - name: Clone EL contracts
        uses: actions/checkout@v2
        with:
          repository: Layr-Labs/eignlayr-contracts
          path: contracts/eignlayr-contracts
          ssh-key: ${{ secrets.EIGENLAYR_DEPLOY_KEY }}
          submodules: recursive
          persist-credentials: true

      - name: Update Submodule Commits
        run: |
          git submodule update --init --recursive contracts/eignlayr-contracts

      - name: Install geth
        run: |
          sudo add-apt-repository -y ppa:ethereum/ethereum
          sudo apt-get update
          sudo apt-get -y install ethereum

      - name: Get geth version
        run: geth version

      - name: Install Foundry
        uses: foundry-rs/foundry-toolchain@v1
        with:
          version: nightly

      - name: Get Forge version
        run: forge --version

      - name: Compile contracts
        run: |
          make compile-el
          make compile-dl

      - name: Download points
        run: |
          mkdir -p ./integration/data/kzg
          wget --no-check-certificate --no-proxy https://datalayr-testnet.s3.amazonaws.com/g1.point.3000 -O ./integration/data/kzg/g1.point
          wget --no-check-certificate --no-proxy https://datalayr-testnet.s3.amazonaws.com/g2.point.3000 -O ./integration/data/kzg/g2.point

      - name: Run tests for lib/encoding
        run: go test -coverprofile=coverage.out ./lib/encoding/...

